"""The one block of the learner's own past that gets threaded into
FinalAnswer's prompt (see loop.py's `_finish_turn_with_fact`) — the
piece that was missing before this module existed: `retrieval.retrieve()`
already ran every turn (feeding `PredictSelection`), but nothing in the
answer-generation path ever read its output. Retrieval was observed,
never used.

Two functions, deliberately separate:

`assemble_history_block` does the I/O — one `retrieve()` call plus one
raw query batch-fetching the full stored row (question/response/
outcome/next-question/abstract) for whichever interactions retrieval
surfaced, since `RetrievalCandidate` itself only carries whichever
single text field (`question_text` or `abstract_form`) won that
candidate's key, not everything this formatter needs to render one.

`render_history_block` is pure string templating — no I/O, no LLM
call. NO LLM CALL ANYWHERE IN THIS MODULE: every field the template
needs (question_text, response_text, abstract_form, next_question_text,
the outcome label) is already stored verbatim or already generated by
the write-side abstractor/classifier. Generating a fresh summary here
would re-summarize already-summarized text, add a call's worth of
latency to every single turn, and make a bad answer impossible to
attribute — good retrieval versus a generation step compensating for
bad retrieval would look identical from the outside. Determinism on
this path is what keeps the result attributable to retrieval quality
specifically.

ONE block, not two: the live turn (the student's message, the resolved
branch, the recent same-session conversation) is already in FinalAnswer's
own prompt via its existing parameters — this module renders none of
that back. Its only job is what the model cannot already see: the
learner's past. The current turn is the lens that past gets framed
through (oldest-first, most-recent-last, right before the live
question), not content restated here.

Population framing: `retrieve()`'s one population-scope candidate is a
pattern across many learners, not this learner's history, and is
rendered in a visibly different voice ("across other learners...") so
it can never be attributed back to this specific learner — the exact
failure the personal/population split (retrieval.py's own module
docstring) exists to prevent, and one that would otherwise be invisible
in the rendered prose.

TEMPLATE_VERSION is bumped whenever the wording changes meaningfully —
logged per turn (see loop.py) so a later regression in answer quality
can be attributed to a specific template revision, not guessed at.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import UTC, datetime
from uuid import UUID

import asyncpg
from pydantic import BaseModel

from probe.domain_config import Domain
from probe.retrieval import RetrievalContext, retrieve
from probe.retrieval_config import RetrievalConfig

TEMPLATE_VERSION = "history-block-v1"

_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")

_OUTCOME_PHRASES: dict[str, str] = {
    "matched": "which showed that answer had actually landed",
    "contradicted_intent": "which showed the earlier answer had missed what they meant",
    "moved_on": "before moving on to something else",
    # 'deferred' deliberately absent: it means "nothing to know yet," not
    # a real signal -- dropped like any other null field, never narrated
    # as an absence.
}


class HistoryBlockConfig(BaseModel):
    """`enabled` defaults on, per this feature's own justification: the
    only way to know whether the history block does anything is running
    the same question both ways and reading both answers -- flip it off
    for that comparison, don't remove the wiring to get it.

    `max_block_chars` (~4 chars/token) keeps prompt size constant
    whether this is session 2 or session 200 -- `retrieve()`'s own
    fixed 4+1 quota already bounds candidate COUNT; this bounds
    rendered TEXT length the same way, since an unusually long
    response_text or abstract_form could otherwise let the block grow
    with history depth after all. If rendered text needs truncating
    routinely, that is a bug (a quota or excerpt cap is undersized),
    not a scaling problem to solve by raising this number.
    """

    enabled: bool = True
    max_excerpt_sentences: int = 2
    max_excerpt_chars: int = 220
    max_block_chars: int = 3200
    # An offer turn (options shown, no response yet) or a turn nothing
    # has classified/abstracted yet renders with only `when`+`asked` --
    # two of the five possible clauses, no answer content at all. That
    # is filler, not history: retrieve() is asked for this many more
    # personal candidates than the final cap so there is always a next
    # one to promote when a candidate like that gets dropped (see
    # `_is_useful_personal_item` / `assemble_history_block`) -- the
    # final rendered count still respects RetrievalConfig.quotas.personal.
    personal_overfetch: int = 8


@dataclass
class HistoryItem:
    """Already-resolved render inputs -- no field here requires further
    I/O or judgment; `render_history_block` only ever reads these."""

    is_population: bool
    source_id: UUID
    when_label: str | None = None  # personal only
    asked: str | None = None  # personal only, verbatim
    chose: str | None = None  # personal only, set only on a resolution turn
    given_excerpt: str | None = None  # personal only, condensed response_text
    next_question: str | None = None  # personal only
    outcome_phrase: str | None = None  # personal only, humanized
    abstract_form: str | None = None  # personal (supporting) or population (primary)
    distinct_learner_count: int | None = None  # population only


def _condense(text: str | None, max_sentences: int, max_chars: int) -> str | None:
    """Pure sentence-boundary truncation -- no generation. "A couple of
    sentences" means the first `max_sentences` sentences of the ALREADY-
    WRITTEN response_text, not a re-written summary of it."""
    if not text:
        return None
    text = text.strip()
    if not text:
        return None
    sentences = [s for s in _SENTENCE_SPLIT.split(text) if s]
    excerpt = " ".join(sentences[:max_sentences]).strip()
    if len(excerpt) > max_chars:
        excerpt = excerpt[:max_chars].rsplit(" ", 1)[0].rstrip(",;:- ") + "…"
    return excerpt or None


def _ensure_period(text: str) -> str:
    text = text.rstrip()
    return text if text.endswith((".", "!", "?", "…")) else text + "."


def _is_useful_personal_item(item: HistoryItem) -> bool:
    """A candidate carrying only `asked` (an offer turn with no
    response, or a turn nothing has classified/abstracted yet) is
    filler -- "what they asked" with nothing about what happened next
    is not history worth a slot. Population items are never filtered
    here (`_population_recall` guarantees `abstract_form` is always
    set on the one row it can return)."""
    return any([item.chose, item.given_excerpt, item.next_question, item.abstract_form])


def _render_personal_paragraph(item: HistoryItem) -> str:
    sentence = f"{item.when_label}, they asked {item.asked!r}"
    if item.chose:
        sentence += f", and when given options, went with {item.chose!r}"
    sentences = [sentence + "."]
    if item.given_excerpt:
        sentences.append(_ensure_period(f"They were told, in short: {item.given_excerpt}"))
    if item.abstract_form:
        sentences.append(_ensure_period(f"The underlying move: {item.abstract_form}"))
    if item.next_question:
        if item.outcome_phrase:
            sentences.append(
                f"They followed up by asking {item.next_question!r}, {item.outcome_phrase}."
            )
        else:
            sentences.append(f"They followed up by asking {item.next_question!r}.")
    return " ".join(sentences)


def _render_population_paragraph(item: HistoryItem) -> str:
    support = (
        f" (seen across {item.distinct_learner_count} learners)"
        if item.distinct_learner_count
        else ""
    )
    pattern_text = item.abstract_form or ""
    return _ensure_period(
        f"Across other learners, not specific to this one{support}, a "
        f"recurring pattern: {pattern_text}"
    )


def render_history_block(
    items: list[HistoryItem], config: HistoryBlockConfig | None = None
) -> str:
    """Pure formatting, no I/O, no LLM call. Empty input -> empty
    string, so a caller with nothing retrieved simply omits the block
    rather than rendering an empty shell."""
    cfg = config or HistoryBlockConfig()
    # Defensive, not the primary mechanism: `assemble_history_block`
    # already overfetches and backfills so a dropped item doesn't
    # shrink the final count below quota, but render_history_block
    # itself must never emit a useless paragraph even if a caller
    # (a test, a future call site) skips that step.
    items = [item for item in items if item.is_population or _is_useful_personal_item(item)]
    if not items:
        return ""
    paragraphs = [
        _render_population_paragraph(item) if item.is_population else _render_personal_paragraph(item)
        for item in items
    ]
    body = "\n\n".join(paragraphs)
    block = (
        "\nBackground on who you are teaching, drawn from their own history "
        "and a broader pattern across other learners. Use it only to set "
        "assumed prior knowledge, vocabulary, depth, and what can be "
        "skipped rather than re-explained -- it is background, not content "
        "to answer from. Never mention or reference it directly (no "
        "\"last time you asked about...\", no \"as you may recall\"): a "
        "tutor who remembers shows it in what gets skipped and assumed, "
        "not by announcing it.\n\n"
        f"{body}\n"
    )
    if len(block) > cfg.max_block_chars:
        truncated = block[: cfg.max_block_chars]
        cut = truncated.rfind("\n\n")
        block = (truncated[:cut] if cut > 0 else truncated) + "\n"
    return block


def _when_label(row_session_id: UUID, row_created_at: datetime, current_session_id: UUID) -> str:
    if row_session_id == current_session_id:
        return "Earlier in this session"
    if row_created_at.astimezone(UTC).date() == datetime.now(UTC).date():
        return "Earlier today"
    return "In an earlier session"


async def assemble_history_block(
    pool: asyncpg.Pool,
    learner_id: UUID,
    session_id: UUID,
    query_vec: list[float],
    retrieval_config: RetrievalConfig | None = None,
    history_config: HistoryBlockConfig | None = None,
    domain: Domain | None = None,
) -> tuple[str, list[UUID]]:
    """The I/O half: one `retrieve()` call (unchanged retrieval ranking
    -- see this module's own docstring) plus one batch query for
    whatever full row data the template needs beyond what
    `RetrievalCandidate` itself carries. Returns the rendered block
    (possibly "") and the source ids it was built from, for the caller
    to log (see loop.py's `_finish_turn_with_fact`).

    `domain`, when given, is the domain switch's one retrieval touch
    (domain_config.py): restricts personal-scope recall to this
    learner's SAME-domain interactions only, so an education run and a
    general run for the same learner_id never blend into one history
    block. None preserves the old, unfiltered behavior.
    """
    cfg = history_config or HistoryBlockConfig()
    if not cfg.enabled:
        return "", []

    # Overfetch personal candidates beyond the final target so a
    # filler item (see _is_useful_personal_item) can be dropped and
    # the next-best candidate promoted, rather than just shrinking the
    # rendered count below quota. retrieve()'s own ranking is
    # untouched -- this only asks it for more of what it already
    # returns, via the same public `config` parameter.
    base_retrieval_config = retrieval_config or RetrievalConfig()
    target_personal = base_retrieval_config.quotas.personal
    overfetch_config = base_retrieval_config.model_copy(
        update={
            "quotas": base_retrieval_config.quotas.model_copy(
                update={"personal": max(cfg.personal_overfetch, target_personal)}
            )
        }
    )

    result = await retrieve(
        pool, learner_id, query_vec,
        ctx=RetrievalContext(domain=domain), config=overfetch_config,
    )
    personal = [c for c in result.candidates if c.scope == "personal"]
    population = [c for c in result.candidates if c.scope == "population"][
        : base_retrieval_config.quotas.population
    ]
    if not personal and not population:
        return "", []

    rows_by_id: dict[UUID, asyncpg.Record] = {}
    if personal:
        ids = [c.source_id for c in personal]
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT i.id, i.session_id, i.created_at, i.question_text,
                       i.question_author, i.originating_question, i.response_text,
                       t.outcome, t.next_question_text,
                       a.abstract_form
                FROM interactions i
                LEFT JOIN LATERAL (
                    SELECT outcome, next_question_text FROM turn_outcomes
                    WHERE interaction_id = i.id ORDER BY seq DESC LIMIT 1
                ) t ON TRUE
                LEFT JOIN LATERAL (
                    SELECT abstract_form FROM interaction_abstracts
                    WHERE interaction_id = i.id ORDER BY seq DESC LIMIT 1
                ) a ON TRUE
                WHERE i.learner_id = $1 AND i.id = ANY($2::uuid[])
                """,
                learner_id,
                ids,
            )
        rows_by_id = {r["id"]: r for r in rows}

    items: list[HistoryItem] = []
    used_ids: list[UUID] = []

    for c in population:
        items.append(
            HistoryItem(
                is_population=True,
                source_id=c.source_id,
                abstract_form=c.text,
                distinct_learner_count=c.distinct_learner_count,
            )
        )
        used_ids.append(c.source_id)

    # Built in `personal`'s own order (retrieve()'s score ranking,
    # preserved through the overfetch) so the usefulness filter below
    # drops the WORST-ranked filler first, not an arbitrary one, before
    # ever touching chronological order.
    ranked_personal_items: list[tuple[datetime, HistoryItem]] = []
    for c in personal:
        row = rows_by_id.get(c.source_id)
        if row is None:
            continue
        is_resolution = row["question_author"] == "system_option"
        asked = row["originating_question"] if is_resolution else row["question_text"]
        chose = row["question_text"] if is_resolution else None
        item = HistoryItem(
            is_population=False,
            source_id=c.source_id,
            when_label=_when_label(row["session_id"], row["created_at"], session_id),
            asked=asked,
            chose=chose,
            given_excerpt=_condense(
                row["response_text"], cfg.max_excerpt_sentences, cfg.max_excerpt_chars
            ),
            next_question=row["next_question_text"],
            outcome_phrase=_OUTCOME_PHRASES.get(row["outcome"]),
            abstract_form=row["abstract_form"],
        )
        ranked_personal_items.append((row["created_at"], item))

    useful_personal_items = [
        pair for pair in ranked_personal_items if _is_useful_personal_item(pair[1])
    ][:target_personal]
    useful_personal_items.sort(key=lambda pair: pair[0])  # oldest first
    items.extend(item for _, item in useful_personal_items)
    used_ids.extend(item.source_id for _, item in useful_personal_items)

    return render_history_block(items, cfg), used_ids
