from datetime import datetime, timezone
from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Learner(BaseModel):
    """Identity-level record only.

    Deliberately thin: label/display_name/preferred_register/timezone
    are the only fields, all optional, none behavioral. What a learner
    knows or is working toward is never tracked here.
    """

    id: UUID = Field(default_factory=uuid4)
    label: str | None = None
    display_name: str | None = None
    preferred_register: str | None = None
    timezone: str | None = None
    created_at: datetime = Field(default_factory=_utcnow)


class NodeCall(BaseModel):
    """One row from node_calls — for read paths (the web UI) that need
    a specific past call's input/output rather than just writing new
    ones (NodeCallStore.record is the only writer, per CLAUDE.md
    invariant 2)."""

    id: UUID
    node_name: str
    session_id: UUID
    turn_index: int
    input_json: dict
    output_json: object
    timestamp: datetime


class TurnRecord(BaseModel):
    """One student turn, as persisted by TranscriptStore.record_turn."""

    id: UUID
    session_id: UUID
    turn_index: int
    text: str
    created_at: datetime


class BranchStatus(str, Enum):
    OPEN = "open"
    MATCHED = "matched"
    UNMATCHED = "unmatched"
    SUPERSEDED = "superseded"


class OptionStatus(str, Enum):
    OPEN = "open"
    SELECTED = "selected"
    SUPERSEDED = "superseded"


class Option(BaseModel):
    """One clickable button — an interpretation-free evidence channel:
    a click is an unambiguous fact about which reading the student
    meant, with no guess about what they said. `branch_id` is a hard
    1:1 mapping onto the branch it confirms.

    Shared verbatim by the disambiguation flow (disambiguate.py /
    `disambiguation_options`); it was the tree-based system's model
    first, hence the name.
    """

    id: UUID = Field(default_factory=uuid4)
    branch_id: UUID
    generation_id: UUID
    session_id: UUID
    turn_index: int
    text: str
    status: OptionStatus = OptionStatus.OPEN
    created_at: datetime = Field(default_factory=_utcnow)


class OptionProposal(BaseModel):
    """DisambiguationOptions' raw per-item output before persistence —
    not itself DB-backed (`Option` is, once IDs/session/turn context
    are attached in loop.py)."""

    branch_id: UUID
    text: str


class DisambiguationTurn(BaseModel):
    """One AssessAndBranch call's identity — the "how did we think
    about this" log entry disambiguate.py's module docstring describes.
    Written unconditionally, whether or not `needs_branches` fires, so
    a turn where the message was judged unambiguous is still a
    queryable row (`needs_branches=False`), not a gap in the record.

    `turn_had_direct_answer` is True exactly when FinalAnswer ran
    against this same turn with no branch context. A click-resolution
    turn never creates one of these rows at all: it re-uses the
    branches already generated by an earlier DisambiguationTurn rather
    than running AssessAndBranch again.
    """

    id: UUID = Field(default_factory=uuid4)
    session_id: UUID
    turn_index: int
    needs_branches: bool
    turn_had_direct_answer: bool
    created_at: datetime = Field(default_factory=_utcnow)


class DisambiguationBranch(BaseModel):
    """One distinct plausible reading of an ambiguous message — flat by
    construction: no `parent_id` (no expansion, ever), no depth, no
    evidence gating, no predicted-next-turn forecast (a click or a
    typed message resolves it directly).

    `status` reuses `BranchStatus`, but only ever visits OPEN, MATCHED
    (via an option click) and SUPERSEDED (every sibling once one is
    clicked, or every branch in a generation the student typed past
    instead of clicking). UNMATCHED is never used: there is no
    prediction to fail to match.
    """

    id: UUID = Field(default_factory=uuid4)
    disambiguation_turn_id: UUID
    session_id: UUID
    turn_index: int
    statement: str
    status: BranchStatus = BranchStatus.OPEN
    created_at: datetime = Field(default_factory=_utcnow)


class DisambiguationAssessment(BaseModel):
    """AssessAndBranch's raw output before persistence — not itself
    DB-backed. Empty `branch_statements` is the normal, expected shape
    whenever `needs_branches` is False, not a parse failure."""

    needs_branches: bool
    branch_statements: list[str] = Field(default_factory=list)


class TurnDiagnostics(BaseModel):
    """One row per turn — the persisted form of what the loop already
    computes each turn (call counts, the MAX_CALLS_PER_TURN guardrail,
    wall-clock duration, warnings, whether the response call failed),
    so the web UI's Diagnostics strip can read it directly instead of
    re-deriving it.

    `retry_count` is this turn's total across every LLMClient retry
    (snapshotted before/after the turn — see loop.py's
    `_total_retry_count`); always 0 against StubLLMClient. `entropy_bits`
    is a nullable legacy column, always None now that the entropy-scaled
    reasoning budget is gone.

    The `memory_*` / `branching_skipped_by_memory` / `matched_fact_id`
    fields are the memory layer's own visibility fields (memory.py) —
    `branching_skipped_by_memory` is the literal behavioral consequence
    a reviewer searches for: AssessAndBranch never ran this turn
    because a past fact was confirmed to resolve the message.
    """

    id: UUID = Field(default_factory=uuid4)
    session_id: UUID
    turn_index: int
    node_call_counts: dict[str, int] = Field(default_factory=dict)
    total_call_count: int = 0
    guardrail_fired: bool = False
    entropy_bits: float | None = None
    duration_ms: float
    warnings: list[str] = Field(default_factory=list)
    teach_failed: bool = False
    retry_count: int = 0
    memory_match_found: bool = False
    memory_match_confirmed_resolution: bool = False
    branching_skipped_by_memory: bool = False
    matched_fact_id: UUID | None = None
    created_at: datetime = Field(default_factory=_utcnow)


class SessionSummary(BaseModel):
    """One row for the Setup page's resume view: a learner's prior
    session and how many turns it has. `topic` is a legacy optional
    kept only so existing read/render sites don't have to change — it
    is always None now that sessions have no concept graph attached.
    """

    session_id: UUID
    topic: str | None = None
    turn_count: int
    created_at: datetime


class LearnerSummary(BaseModel):
    """One row for the Setup page's existing-learner picker: a learner
    plus their session count and most recent session's timestamp
    (None if they have no sessions yet)."""

    learner: Learner
    session_count: int
    last_session_at: datetime | None


class LearnerFactType(str, Enum):
    BRANCH_RESOLUTION = "branch_resolution"
    DIRECT_ANSWER = "direct_answer"


class LearnerFact(BaseModel):
    """One row of the memory layer's durable, per-learner record (see
    memory.py's module docstring) — plain English, written every turn
    a real resolution happened (a click resolved an ambiguity, or
    FinalAnswer answered directly), never on a turn that only raised
    options with nothing yet decided.

    `situation`/`resolution` are always in "the student's own terms,"
    not restated jargon. `embedding` is over the combined
    situation+resolution text (see memory.WriteLearnerFact), so a
    search on either half of a past fact can still surface it.

    Append-only (CLAUDE.md invariant 10): a fact is never edited or
    superseded once written.
    """

    id: UUID = Field(default_factory=uuid4)
    learner_id: UUID
    session_id: UUID
    turn_index: int
    fact_type: LearnerFactType
    situation: str
    resolution: str
    embedding: list[float]
    source_turn_id: UUID
    created_at: datetime = Field(default_factory=_utcnow)


class ExtractedFact(BaseModel):
    """WriteLearnerFact's own node output (not DB-backed) — deliberately
    excludes the embedding vector and every id: a node's `output_json`
    in node_calls should read as a human-checkable fact, not carry a
    768-float array nobody will ever read there."""

    situation: str
    resolution: str


class FactSearchResult(BaseModel):
    """EmbedAndSearchFacts' own node output — the nearest learner_facts
    match (if any) and its cosine similarity, without the matched
    fact's embedding for the same node_calls-readability reason as
    ExtractedFact. `matched_fact_id` is None when the learner simply
    has no facts yet (a new learner, or turn 0) — not an error."""

    matched_fact_id: UUID | None = None
    situation: str | None = None
    resolution: str | None = None
    similarity: float | None = None


class FactMatchConfirmation(BaseModel):
    """ConfirmFactMatch's output — a strong vector-similarity hit is
    not itself proof the matched fact resolves THIS message; this is
    the structured judgment call that decides whether the memory
    pre-check is actually allowed to skip branching."""

    resolves: bool


class PathSummary(BaseModel):
    """SummarizeSessionPath's output — a label for the STRUCTURE of one
    session's ordered facts (e.g. "concrete example requested before
    abstract definition, repeatedly"), deliberately abstract enough to
    apply regardless of topic. Not itself a claim about the learner."""

    summary: str


class ThinkingStyleConfirmation(BaseModel):
    """ConfirmThinkingStyleMatch's output — does this session's labeled
    path genuinely share the same order-structure as an existing
    candidate, or only a superficial resemblance? Only a True here
    advances ThinkingStyleCandidate.confirmation_count/session_ids."""

    confirms: bool


class ThinkingStyleStatus(str, Enum):
    CANDIDATE = "candidate"
    CONFIRMED = "confirmed"
    RETIRED = "retired"


class ThinkingStyleCandidate(BaseModel):
    """A hypothesized, cross-session order-structure for one learner —
    e.g. "wants a concrete example before an abstract rule, regardless
    of topic." Starts life as `candidate` (confirmation_count=1) and
    stays there, accumulating independent confirmations, until
    `confirmation_count` crosses
    `MemoryConfig.thinking_style_promotion_threshold` — only then does
    it become `confirmed` and only then does it get fed into any live
    session's prompts.

    `confirmation_count`/`session_ids` only ever grow via an explicit
    `ConfirmThinkingStyleMatch` call saying yes.

    Append-only (CLAUDE.md invariant 10): `retired` is a status
    transition via UPDATE, same resurrection-over-deletion principle as
    every other store in this project.
    """

    id: UUID = Field(default_factory=uuid4)
    learner_id: UUID
    session_ids: list[UUID]
    path_summary: str
    path_summary_embedding: list[float]
    confirmation_count: int = 1
    status: ThinkingStyleStatus = ThinkingStyleStatus.CANDIDATE
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)


class GroundingEvidence(BaseModel):
    """One web excerpt threaded into `FinalAnswer`'s prompt — the
    single result kept from a time-sensitivity search (grounding.py).

    Not DB-backed: it lives only in this turn's `node_calls` row, which
    is deliberate. A `learner_fact` records what the *student*
    established; a stale-topic excerpt is a fact about the world at
    one moment, and writing it into the durable memory layer would let
    today's answer silently become tomorrow's remembered truth.
    """

    url: str
    title: str | None = None
    publish_date: str | None = None
    excerpt: str


class GroundingResult(BaseModel):
    """`GroundTimeSensitive`'s output — deliberately records the
    negative case too, not just hits.

    `time_sensitive=False` with `matched_marker=None` is the normal,
    expected shape on an ordinary turn, and it is written to
    `node_calls` on every turn this node runs. That is the point: the
    check's real firing rate is a measurable property of the audit
    trail rather than something inferred from how often a search
    happened to appear.

    `error` is set when a search was attempted and failed — the
    explicit, logged record of a degradation to an ungrounded answer,
    so the fallback can never be a silent one.

    `evidence` is a ranked list, not a single excerpt. It was a single
    excerpt originally, and that was a measured mistake: on a live
    comparison run the top-ranked result for "latest stable Python
    version" was the authoritative domain but its excerpt was a
    glossary of release *phases* containing no version number, while
    results 2 and 3 both carried the answer and were discarded. The
    grounded answer came out less accurate than the ungrounded one AND
    wearing a citation. Ranked-but-diverse beats single-best here.
    """

    time_sensitive: bool = False
    matched_marker: str | None = None
    searched: bool = False
    evidence: list[GroundingEvidence] = Field(default_factory=list)
    error: str | None = None


class EvidenceSourceType(str, Enum):
    # A deliberate scripted run to exercise a code path — proves a
    # mechanism functions, never that the system adapted to a real
    # student.
    STAGED_VERIFICATION = "staged_verification"
    # A finding lifted from a real, organic student session.
    ORGANIC_SESSION = "organic_session"


class EvidenceRecord(BaseModel):
    """One recorded verification finding (evidence_records, migration
    033). `source_type` is load-bearing: it keeps a staged mechanism
    test visibly separate from evidence produced by real usage, so the
    Evidence page can never present the former as the latter.

    `body` is the structured verbatim evidence for this finding
    (branches offered, facts written, `turn_diagnostics` fields,
    responses, consolidation output, …). `summary` is the one-line read
    — for `STAGED_VERIFICATION` it must use "mechanism verified"
    language, never "adapted to the student" (enforced by the writer,
    not the schema).

    Append-only (CLAUDE.md invariant 11): a finding is never edited or
    removed once written.
    """

    id: UUID = Field(default_factory=uuid4)
    source_type: EvidenceSourceType
    part: str
    title: str
    summary: str
    body: dict = Field(default_factory=dict)
    learner_id: UUID | None = None
    session_id: UUID | None = None
    created_at: datetime = Field(default_factory=_utcnow)
