name: versa_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  file_picker: ^13.1.0
  firebase_auth: ^6.7.0
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  http: ^1.6.0
  image_picker: ^1.2.3
  provider: ^6.1.5+1
  purchases_flutter: ^10.13.0
  purchases_ui_flutter: ^10.13.0
  shared_preferences: ^2.5.5
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
